packageExtensions:
  "@nestjs/apollo@*":
    dependencies:
      tslib: latest
    peerDependencies:
      graphql: ^16.0.0
  "@nestjs/graphql@*":
    peerDependenciesMeta:
      class-transformer:
        optional: true
      class-validator:
        optional: true

  "ink-testing-library@*":
    peerDependencies:
      ink: "^3.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
