packageExtensions:
  "@nestjs/graphql@*":
    peerDependenciesMeta:
      class-validator:
        optional: true

      class-transformer:
        optional: true

  graphql.macro@*:
    peerDependencies:
      "@babel/core": "*"
      "@babel/runtime": "*"
      graphql: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
