plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
#  - path: packages/yarn/bundles/@yarnpkg/plugin-jill.js
#    spec: "@yarnpkg/plugin-jill"

yarnPath: .yarn/releases/yarn-berry.cjs
