name: 'Check PR'

on:
  pull_request:
    branches: [ master, next ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        id: lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build:prod

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Test
        run: yarn test --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  e2e:
    runs-on: ${{ matrix.os }}
    needs: [ build ]

    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        node:
          - 16
          - 18
        packageManager:
          - npm
          - yarn

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Use Node.js ${{ matrix.node }}.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: dist

      - name: Git setup
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Test
        run: yarn e2e --verbose
        env:
          USE_PACKAGE_MANAGER: ${{ matrix.packageManager }}

  complete:
    runs-on: ubuntu-latest
    needs: [ lint, build, tests, e2e ]
    if: ${{ always() }}

    steps:
      - name: Failed
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: Success
        run: echo 'You are soooo curious ;)'

  sonarcloud:
    if: ${{ !startsWith(github.head_ref, 'renovate/') && !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest
    needs: [ tests ]

    steps:
      - uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Download test coverage
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: coverage
          path: coverage

      - name: Load package.json
        id: info
        run: echo "version=$(jq -r ".version" package.json)" >> $GITHUB_OUTPUT

      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@v1.9
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.info.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
