name: 'EsLint'

on:
  push:
    branches: [ master, next ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write
    
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint -f @microsoft/sarif -o eslint-results.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
