name: 'Pull Request'

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - uses: actions/cache@v2.1.6
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: built-code
          path: packages/*/dist/*

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - '@jujulego/jill'
          - '@jujulego/jill-core'

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - uses: actions/cache@v2.1.6
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace ${{ matrix.package }} lint

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]

    strategy:
      matrix:
        include:
          - workspace: 'packages/cli'
            package: '@jujulego/jill'

          - workspace: 'packages/core'
            package: '@jujulego/jill-core'

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - uses: actions/cache@v2.1.6
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v2
        with:
          name: built-code
          path: packages

      - name: Test
        run: yarn workspace ${{ matrix.package }} test

      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: ${{ matrix.workspace }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
