name: 'Release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release-notes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Prepare
        id: prepare
        # language=Bash
        run: |
          tag=$(echo '${{ github.ref }}' | cut -d / -f 3-)
          version=$(echo $tag | cut -d _ -f 2)
          
          echo "version=$version" >> $GITHUB_OUTPUT
          
          if [[ $version =~ "^[0-9]+\.[0-9]+\.[0-9]-[a-zA-Z]+\.[0-9]+" ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.prepare.outputs.version }}
          generate_release_notes: true
          prerelease: ${{ steps.prepare.outputs.prerelease }}

      - name: Finalize Sentry Release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
        with:
          release: 'jill@${{ steps.prepare.outputs.version }}'
          environment: production
          finalize: true
