name: 'Release'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release-notes:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Read tag
        id: info
        run: |
          tag=`echo '${{ github.ref }}' | cut -d / -f 3-`
          
          echo version=`echo $tag | cut -d _ -f 2` >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.info.outputs.version }}
          draft: true
          generate_release_notes: true